geektwitter3/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'tweets#index'
  resources :tweets, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

geektwitter3/app/models/tweet.rb
class Tweet < ApplicationRecord
end

geektwitter3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

geektwitter3/app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to :action => "show", :id => @tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    Tweet.find(params[:id]).destroy
    redirect_to action: :index
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body)
  end
end

geektwitter3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geektwitter3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

geektwitter3/app/views/tweets/edit.html.erb
<h1>Tweets#edit</h1>
<p>Find me in app/views/tweets/edit.html.erb</p>

<%= form_for @tweet do |f| %>
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %> 
    <%= f.submit "編集する" %>
<% end %>

geektwitter3/app/views/tweets/index.html.erb
<h1>Tweets#index</h1>
<p>Find me in app/views/tweets/index.html.erb</p>
<%= link_to "新規投稿ページへ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
    <div class="tweet">
      <%= t.body %>
      <%= t.created_at %>
      <%= link_to "詳細へ", tweet_path(t.id) %>
      <%= link_to "編集する", edit_tweet_path(t.id) %>
      <%= link_to "削除する", tweet_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

<a class="btn btn-primary" href="#" role="button">Link</a>
<button class="btn btn-primary" type="submit">Button</button>
<input class="btn btn-primary" type="button" value="Input">
<input class="btn btn-primary" type="submit" value="Submit">
<input class="btn btn-primary" type="reset" value="Reset">

geektwitter3/app/views/tweets/new.html.erb
<h1>GeekTwitter</h1>
<p>Find me in app/views/tweets/new.html.erb</p>
<h3>新規Tweet</h3>
<%= form_for @tweet do |f| %>
  <div class="field">
    <%= f.label :body %>
    <%= f.text_field :body, :size => 140 %>
  </div>
  <%= f.submit "Tweetする" %>
<% end %>
<%= link_to "Tweet一覧に戻る", tweets_path %>

geektwitter3/app/views/tweets/show.html.erb
<h1>GeekTwitter</h1>
<p>Find me in app/views/tweets/show.html.erb</p>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
  <%= link_to "編集する", edit_tweet_path(@tweet.id) %>
</div>
<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">Tweet詳細</h5>
    <p class="card-text"><%= @tweet.body %></p>
    <%= link_to "編集する", edit_tweet_path(@tweet.id), :class => "btn btn-primary" %>
  </div>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>